#INDICA QUE VERSION DE NODEJS NECESITA EL PROYECTO
FROM node:12

#CREAR UNA CARPETA DONDE ESTARA EL DIRECTORIO DE TRABAJO
WORKDIR /app

#COPIAR LOS ARCHIVOS QUE NECESITA EL SISTEMA PARA FUNCIONAR. EL ./ HACE REFERENCIA A /app
#EL * INDICA QUE
COPY package*.json ./

RUN npm install

#COPIAR ARCHIVOS FUENTE
COPY . .

CMD ["npm","start"]